# Generated by Django 3.0.3 on 2020-02-20 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200212_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coordinator',
            field=models.CharField(max_length=100, verbose_name='Coordinator :'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_contact',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_1',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Satisfactory', 'Satisfactory'), ('Needs Improvement', 'Needs Improvement')], max_length=20, verbose_name='How is your relationship with your student?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_1a',
            field=models.TextField(blank=True, verbose_name='Comments :'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_2',
            field=models.TextField(blank=True, verbose_name='Please Tell me about an experience you had this month with your student that differs from last month (REQUIRED).'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_3',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='* Do you feel your student is improving his/her level of conversational english?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_3a',
            field=models.TextField(blank=True, verbose_name='If yes, provide examples of how your student has improved in this area:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_3b',
            field=models.TextField(blank=True, verbose_name='If no, provide examples of specific areas you feel your student can improve upon to help strengthen his/her level of English:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_4',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='Has your student interacted with your family this month?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_4a',
            field=models.TextField(blank=True, verbose_name='If yes, provide examples of how your student interacted with your family this month:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_4b',
            field=models.TextField(blank=True, verbose_name='If no, provide examples of how your student can better interact with your family:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_5',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='Has your student made plans with any American friends or shown any interest in events in the community?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_5a',
            field=models.TextField(blank=True, verbose_name='If yes, please provide details:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_6',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='Does your student obey the rules at home this month?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_6a',
            field=models.TextField(blank=True, verbose_name='If no, please provide details so MAH can counsel the student to better improve in this area:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_7',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Satisfactory', 'Satisfactory'), ('Needs Improvement', 'Needs Improvement')], max_length=20, verbose_name='Rate your hosting experience so far:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_7a',
            field=models.TextField(blank=True, verbose_name="Host Family's Comments :"),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_coordinator_comments',
            field=models.TextField(blank=True, verbose_name="Coordinator's comments re: Host Family progress this month (REQUIRED):"),
        ),
        migrations.AlterField(
            model_name='post',
            name='hf_hostfamily_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="HOST FAMILY'S LAST NAME"),
        ),
        migrations.AlterField(
            model_name='post',
            name='hostfamily',
            field=models.CharField(max_length=100, verbose_name='Host Family Name :'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Add Photo of Student Interacting with Host Family below:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_1a',
            field=models.CharField(blank=True, max_length=100, verbose_name="School Contact's Name:"),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_1b',
            field=models.CharField(blank=True, max_length=100, verbose_name="School Contact's Title"),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_2',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Satisfactory', 'Satisfactory'), ('Needs Improvement', 'Needs Improvement')], max_length=20, verbose_name="What is the school's impression of the student's academic performance this month?"),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_2a',
            field=models.TextField(blank=True, verbose_name="School's feedback about student's academic performance this month:"),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_3',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='Has the student had any accomplishments (e.g., honor roll, athletics, club participation)?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_3a',
            field=models.TextField(blank=True, verbose_name='Please list details re: accomplishments:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_4',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='Has the student missed any days from school'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_4a',
            field=models.IntegerField(default=0, verbose_name='# of Days Missed'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_4b',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='Were these excused absences?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_4c',
            field=models.TextField(blank=True, verbose_name="School's Comments re: student's attendance:"),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_5',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='Does the student need additional help at school, such as tutoring, or is there any area(s) MAH can counsel the student to help him/her improve in this area?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_5a',
            field=models.CharField(blank=True, max_length=100, verbose_name="School's Comments re:"),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_6',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name="Is the student receiving a 'C' or better in each class?"),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_classes_grades',
            field=models.TextField(blank=True, verbose_name='List all classes & current grades this month below.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_school_name',
            field=models.CharField(blank=True, max_length=50, verbose_name="SCHOOL'S NAME"),
        ),
        migrations.AlterField(
            model_name='post',
            name='sch_student_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Student's Name"),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_1',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Satisfactory', 'Satisfactory'), ('Needs Improvement', 'Needs Improvement')], max_length=50, verbose_name='How are you getting along with your host family?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_1a',
            field=models.TextField(blank=True, verbose_name='Comments :'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_2',
            field=models.TextField(blank=True, verbose_name='Please Tell me about an experience you had this month at school that differs from last month (REQUIRED).'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_3',
            field=models.TextField(blank=True, verbose_name='Please Tell me about an experience you had this month with your host family that differs from last month (REQUIRED).'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_4',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='Do you feel you are improving your conversational english?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_4a',
            field=models.TextField(blank=True, verbose_name='If yes, provide examples of how you have improved your conversational level of English:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_4b',
            field=models.TextField(blank=True, verbose_name='If no, provide examples of areas you would like to improve upon to help strengthen your level of English:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_5',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='* Have you made new American friends & interests in the community or school?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_5a',
            field=models.TextField(blank=True, verbose_name='If yes, provide details:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_6',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Satisfactory', 'Satisfactory'), ('Needs Improvement', 'Needs Improvement')], max_length=20, verbose_name='* How do you feel you are doing in school?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_6a',
            field=models.CharField(blank=True, max_length=100, verbose_name='What is your favorite subject this month?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_6b',
            field=models.CharField(blank=True, max_length=100, verbose_name='What subject are you having trouble with this month?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_7',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='* Did you experience any issues this month with your host family or at School?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_7a',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='Is there anything you would like to talk about or need help with?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_7b',
            field=models.TextField(blank=True, verbose_name="Student's Comments:"),
        ),
        migrations.AlterField(
            model_name='post',
            name='st_coordinator_comments',
            field=models.TextField(blank=True, verbose_name="Coordinator's comments re: Student's progress this month (REQUIRED):"),
        ),
        migrations.AlterField(
            model_name='post',
            name='student_eng_name',
            field=models.CharField(max_length=100, verbose_name="Student's English Name :"),
        ),
        migrations.AlterField(
            model_name='post',
            name='student_surname',
            field=models.CharField(max_length=100, verbose_name="Student's Surname :"),
        ),
    ]
